### ISSUE TITLE
Could not find method compile() for arguments [org.aspectj:aspectjrt:1.8.9] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler. Open File

### ISSUE THREAD

**Issue by HexScience** [JingYeoh/FragmentRigger#61]
I get this error while compiling app.

Could not find method compile() for arguments [org.aspectj:aspectjrt:1.8.9] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Main gradle**
dependencies {
classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.1'
        classpath 'org.aspectj:aspectjtools:1.8.13'
}
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven {url "https://clojars.org/repo/"}
        maven { url 'https://jitpack.io' }
    }
}

**app gradle**
apply plugin: 'android-aspectjx'
apply plugin: 'com.android.application'
annotationProcessor "com.justkiddingbaby:fragment-rigger:1.4.3"

**Comment by JingYeoh** [comment]
@HexScience  use `implementation ` replace `annotationProcessor ` in your `app gradle` and try again.
