### ISSUE TITLE
使用的一个问题

### ISSUE THREAD

**Issue by oksimple** [JingYeoh/FragmentRigger#67]
创建fragment的时候必须要给一个 Bundle 就算是空的也要给，否则报错

**Comment by JingYeoh** [comment]
@oksimple 请附上错误信息

**Comment by gangoogle** [comment]
![image](https://user-images.githubusercontent.com/19320303/55274028-4132b300-530e-11e9-989b-4b07926e037e.png)
是这个吧

**Comment by JingYeoh** [comment]
@gangoogle 请确认是否开启了混淆？

**Comment by gangoogle** [comment]
> @gangoogle 请确认是否开启了混淆？

这个问题的原因我找到了，那就是创建fragment的时候要设置一个空的sArguments

**Comment by gangoogle** [comment]
> > @gangoogle 请确认是否开启了混淆？
> 
> 这个问题的原因我找到了，那就是创建fragment的时候要设置一个空的sArguments

否则在FragmentRigger->initResultParams()方法中bundle会空指针

**Comment by JingYeoh** [comment]
这个问题已经修复在了 `1.4.4` 版本 https://github.com/JingYeoh/FragmentRigger/pull/69
